export const SEARCH_PARAM_CONFIGS = {
  SEARCH_MIN_SIZE: 0,
  SEARCH_MAX_SIZE: 50,
  SEARCH_MIN_DEAL_AMOUNT: 0,
  SEARCH_MAX_DEAL_AMOUNT: 50,
  SEARCH_MIN_HOUSEHOLD_COUNT: 0,
  SEARCH_MAX_HOUSEHOLD_COUNT: 5000,
} as const;
