export const STORAGE_KEY = {
  TRANSACTION_QUERY_PARAMS: 'JIBSAYO:TRANSACTION_QUERY_PARAMS',
  TRANSACTION_LIST_VIEW_SETTINGS: 'JIBSAYO:TRANSACTION_LIST_VIEW_SETTINGS',
  FAVORITE_REGION_LIST: 'JIBSAYO:FAVORITE_REGION_LIST',
  FAVORITE_APART_LIST: 'JIBSAYO:FAVORITE_APART_LIST',
  RECENT_SEARCHED_APART_LIST: 'JIBSAYO:RECENT_SEARCHED_APART_LIST',
} as const;
