export const STORAGE_KEY = {
  TRANSACTION_SEARCH_FORM: 'JIBSAYO:TRANSACTION_SEARCH_FORM',
  TRANSACTION_QUERY_PARAMS: 'JIBSAYO:TRANSACTION_QUERY_PARAMS', // 모든 쿼리 파라미터 저장
  FAVORITE_REGION_LIST: 'JIBSAYO:FAVORITE_REGION_LIST',
  FAVORITE_APART_LIST: 'JIBSAYO:FAVORITE_APART_LIST',
  TRANSACTION_LIST_RESPONSE: 'JIBSAYO:TRANSACTION_LIST_RESPONSE',
  TRANSACTION_LIST_VIEW_SETTINGS: 'JIBSAYO:TRANSACTION_LIST_VIEW_SETTINGS',
} as const;
